name: Safety
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: https://git.quad4.io/actions/checkout@a5b3063b1edaa6ba4911c8a1b1d5e1656fba3ea5 # v6.0.1
      - name: Run Safety CLI to check for vulnerabilities
        uses: https://git.quad4.io/actions/safety-action@c14ed93c5cacd34d2ac287fe5d0622f697d6a5f4 # v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
